export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <a href="localhost:3000/About">About</a>
      <br></br>
      <a href="localhost:3000/Contact">Contact</a>
      <br></br>
      <a href="localhost:3000/slug">slug</a>
      <br></br>
      <a href="localhost:3000">Home</a>
      <br></br>
    </html>
  );
}
